name: Update HiddenAPI source

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run the tool
        run: |
          rm -rf models
          docker run \
            -v "${PWD}/models:/app/models" \
            -e UAH_USERNAME=${{ secrets.UAH_USERNAME }} \
            -e UAH_ACCOUNT_ID=${{ secrets.UAH_ACCOUNT_ID }} \
            -e UAH_PASSWORD=${{ secrets.UAH_PASSWORD }} \
            ghcr.io/datadog/undocumented-aws-api-hunter:latest
      - name: Commit files
        run: |
          git fetch origin
          git pull origin main
          git config --local user.email "githubbot@hidden-api"
          git config --local user.name "HiddenAPI [bot]"
          git add ./models
          git commit -m "Update new models" || exit 0
          git push